### ISSUE TITLE
Clone in plugins

### ISSUE THREAD

**Issue by PatelUtkarsh** [voronkovich/phpcs.plugin.zsh#2]
I tried cloning this in `.oh-my-zsh/plugins` and adding phpcs in plugins var in `.zshrc` but it didn't work, `$fpath` variable is having phpcs path correctly. 

Also, `source path` isn't working for me somehow.

**Comment by voronkovich** [comment]
@PatelUtkarsh, could you please provide your .zshrc here?

**Comment by PatelUtkarsh** [comment]
https://gist.github.com/PatelUtkarsh/77a39ad5c4abc731667c19fed2863e2a @voronkovich

**Comment by voronkovich** [comment]
@PatelUtkarsh, I can't reproduce this bug on my machine with your `.zshrc`. Autocompletion works as expected. Try this: https://github.com/robbyrussell/oh-my-zsh/wiki/Troubleshooting#completion-problems

**Comment by PatelUtkarsh** [comment]
@voronkovich Thank you for your help.
>First, try to remove your completion cache with rm ~/.zcompdump*, close and reopen your shells.

This worked!

**Comment by PatelUtkarsh** [comment]
Currently, I am using it as a plugin.
